### ISSUE TITLE
Tracking browser bugs

### ISSUE THREAD

**Issue by mathiasbynens** [badges/gh-badges#5]
- [ ] [Chrome/Opera + retina display = blurry](https://code.google.com/p/chromium/issues/detail?id=331387)
- [ ] [Safari + retina display = blurry](https://bugs.webkit.org/show_bug.cgi?id=126398)
- [ ] [Firefox + retina display + `background: url(svg)` = blurry](https://bugzilla.mozilla.org/show_bug.cgi?id=956134)
- [x] [Firefox: greenish aura around the text](https://bugzilla.mozilla.org/show_bug.cgi?id=812795)

**Comment by mathiasbynens** [comment]
Noticed the rendering is different when viewing the SVG file standalone rather than through `<img src=svg>`. Filed https://code.google.com/p/chromium/issues/detail?id=331387.

**Comment by espadrine** [comment]
Oooh, I thought it was independent of that; I submitted a bug report about _zooming_: https://code.google.com/p/chromium/issues/detail?id=331385, but apparently retina causes the same issues?

**Comment by mathiasbynens** [comment]
WebKit has the same issue: https://bugs.webkit.org/show_bug.cgi?id=126398

**Comment by alrra** [comment]
@espadrine @mathiasbynens does specify the [`text-rendering` property](http://www.w3.org/TR/SVG/painting.html#TextRenderingProperty) with the value `"geometricPrecision"` help ? (this should inform the browser to take more time to render things correctly).

**edit:** [Here](http://jsbin.com/aHikuga/1) is something I've been playing with. Does it it make any difference for you guys ? (the first is the original image, the second is the `svg` that uses the `text-rendering` property + has some other changes, while the third is the `svg` from this repository).

**Comment by espadrine** [comment]
@alrra If you zoom the page, you should see that it becomes blurry.

(I haven't checked on a retina display, but zooming and being on retina seems to have the same effects.)

That said, it does look better.

**Comment by mathiasbynens** [comment]
Screenshots of @alrra’s test page on a retina display: http://jsbin.com/aHikuga/1

#### Without zoom (100% zoom)

![](http://i.imgur.com/ug8zeHN.png) )

#### 150% zoom

![](http://i.imgur.com/ZLTXNvZ.png)

It definitely looks better, not as blurry, but still not as sharp as it should be. It feels like viewing @1x image on a @2x screen.

**Comment by espadrine** [comment]
Apparently, this issue was fixed here in Firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=600207.

Also, here is the comparison between Firefox and Chrome, zoomed 2x, using `text-rendering`:

Chrome
![chrome](https://f.cloud.github.com/assets/100689/1835851/73a63826-73f7-11e3-9d01-53e4ac1c84ed.png)

Firefox
![firefox](https://f.cloud.github.com/assets/100689/1835853/780bd8c6-73f7-11e3-88d6-351044ee34b7.png)

(see `data:text/html,<img src='https://thefiletree.com/gh-badges/cheez-whiz.svg?plug=none'>`).

**Comment by espadrine** [comment]
For the purpose of adoption, I think we should omit the text shadow until at least https://code.google.com/p/chromium/issues/detail?id=331387 is fixed.

I'm just going to paste the filter used here for future me's sake.

``` xml
<filter id="shadow">
  <feOffset dx="0" dy="1" in="SourceAlpha"/>
  <feColorMatrix type="matrix" values="1 0 0 0 0  0 1 0 0 0  0 0 1 0 0  0 0 0 .3 0"/>
  <feMerge>
    <feMergeNode/>
    <feMergeNode in="SourceGraphic"/>
    <feMergeNode in="SourceGraphic"/>
  </feMerge>
</filter>
```

**Comment by mathiasbynens** [comment]
b817b570100669a42d5d9eb5c12b159711b02470 :+1:
